name: CI

on:
  push:
    branches:
      - main  # Adjust to your default branch if different
  pull_request:
    branches:
      - main  # Adjust to your default branch if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with verbose output
      run: |
        pytest -v test_auth.py  # Change to your main test command if needed
